version: 2

builds:
  - main: ./cmd/mnemonic
    binary: mnemonic
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

brews:
  - repository:
      owner: Napageneral
      name: homebrew-tap
    homepage: https://github.com/Napageneral/mnemonic
    description: Mnemonic unified memory system

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
